domain: gihc.online
simply_account: "{{ vault_simply_account }}"
simply_api_key: "{{ vault_simply_api_key }}"
acme_email: kristian.n.jensen@gmail.com
vps_ip: "65.109.233.92"

project_dir: /opt/score
platform_dir: /opt/platform

postgres_db: scoredb
postgres_user: scoreuser
test_postgres_db: scoredb_test
beta_postgres_db: scoredb_beta

frontend_domain: "er-det-noget-vaerd.apps.gihc.online"
api_subdomain: "score.api"
base_url: "https://score.api.gihc.online/v1"
frontend_url: "https://er-det-noget-vaerd.apps.gihc.online"
allowed_origin: "https://er-det-noget-vaerd.apps.gihc.online"
resend_from: "noreply@gihc.online"

beta_frontend_domain: "beta.er-det-noget-vaerd.apps.gihc.online"
beta_api_subdomain: "beta.score.api"
beta_base_url: "https://beta.score.api.gihc.online/v1"
beta_frontend_url: "https://beta.er-det-noget-vaerd.apps.gihc.online"
beta_allowed_origin: "https://beta.er-det-noget-vaerd.apps.gihc.online"

test_frontend_domain: "test.er-det-noget-vaerd.apps.gihc.online"
test_api_subdomain: "test.score.api"
test_base_url: "https://test.score.api.gihc.online/v1"
test_frontend_url: "https://test.er-det-noget-vaerd.apps.gihc.online"
test_allowed_origin: "https://test.er-det-noget-vaerd.apps.gihc.online"
